build: main.cpp utils.hpp partition.hpp
	g++ -std=c++11 main.cpp utils.hpp partition.hpp -o output -lpthread
brun: main.cpp utils.hpp partition.hpp
	g++ -std=c++11 main.cpp utils.hpp partition.hpp -o output -lpthread
	./output
run:
	./output
clean:
	rm output
